language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
install:
  - pip install -r requirements.txt --use-mirrors
  - pip install -r requirements-test.txt --use-mirrors
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install --use-mirrors ordereddict; fi
script:
  - python setup.py test
notifications:
  email:
    - tbekolay@gmail.com